[project]
name = "rpa-extracts"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "camelot-py>=1.0.9",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "pdfplumber>=0.11.7",
    "tqdm>=4.67.1",
]
